#!/bin/sh -ex
eval "$(passive-dns-dump-config)"

merge () {
    DIR=$1
    cd $DIR
    rm -rf to_merge

    mkdir to_merge
    mv *.txt to_merge
    passive-dns-merge dns_merged.txt to_merge/*
}


merge ${DATADIR}/by_answer
merge ${DATADIR}/by_query
